OPENAI_API_KEY = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIiwic3ViamVjdCI6ImFwaS1rZXk6NDFhMzhlZjMtNmRmYi00NmEzLTgyNzYtMTY0ZTEzMWY1YThiIn0.ukc0cT77C5iSu9uoKEEtfIAWHt1xjHkAnspzK0K5eRA

QDRANT_URL = https://4c759ad7-4ff4-48f5-aa2c-4e7443a09593.sa-east-1-0.aws.cloud.qdrant.io

QDRANT_API_KEY = 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